services:
  botica-postgres:
    image: postgres:16
    container_name: botica-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-botica_inteligente_db}
      POSTGRES_USER: ${POSTGRES_USER:-botica_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-botica_password}
    ports:
      - "5432:5432"
    volumes:
      - botica_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-botica_user} -d ${POSTGRES_DB:-botica_inteligente_db}"]
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  botica_postgres_data:
