spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/botica_inteligente_db}
    username: ${DB_USERNAME:botica_user}
    password: ${DB_PASSWORD:botica_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/botica-inteligente}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: warn

app:
  cors:
    allowed-origins:
      - http://localhost:4200
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
    allow-credentials: true
