spring:
  application:
    name: Asistente-y-Gestion-de-Botica-Inteligente
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/botica_inteligente_db?currentSchema=botica}
    username: ${DB_USERNAME:botica_user}
    password: ${DB_PASSWORD:botica_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: botica
        format_sql: false
        hbm2ddl.create_namespaces: true
  security:
    jwt:
      secret: ${JWT_SECRET:482e9603e5c9425026df2314545582f3482e9603e5c9425026df2314545582f3482e9603e5c9425026df2314545582f3}
      expiration: ${JWT_EXPIRATION:86400000}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/botica-inteligente}
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/realms/botica-inteligente/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8080}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type
      - Accept
    allow-credentials: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: warn
