spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/botica_inteligente_db?currentSchema=botica}
    username: ${DB_USERNAME:botica_user}
    password: ${DB_PASSWORD:botica_password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/botica-inteligente}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: warn

app:
  cors:
    allowed-origins:
      - http://localhost:4200
