spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/botica_inteligente_db?currentSchema=botica}
    username: ${DB_USERNAME:botica_user}
    password: ${DB_PASSWORD:botica_password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: ${JWT_SECRET:482e9603e5c9425026df2314545582f3482e9603e5c9425026df2314545582f3}
      expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: warn

app:
  cors:
    allowed-origins:
      - http://localhost:5173
      - http://127.0.0.1:5173
